added projects in data
jayk-gupta/Code-Nexus pull request #16
Opened 2023-05-01 18:26 UTC by Madanraj0519

## Description
This pull request was automatically created by a GitHub Action. It contains changes to improve the project and fix issues.

## Changes
I have added one of the Beginner Friendly Opensource Projects in the data. File

## Screenshots (if applicable)
- <screenshots or other visual aids>

## Checklist
- [ ] I have tested the changes locally
- [ ] I have updated the documentation if necessary
- [ ] I have added tests to cover the changes
- [ ] I have reviewed the changes and ensured they are of high quality

## Additional Comments
- <any additional comments or information>

2023-05-02 04:56 UTC, jayk-gupta requested changes
Add original repo link : https://github.com/shyamtawli/devFind
You have added your forked link.

2023-05-02 04:58 UTC, jayk-gupta requested changes

2023-05-02 04:58 UTC, jayk-gupta commented on src/database/data.json
> +    "ghLink": "https://github.com/Madanraj0519/devFind"
```suggestion
    "ghLink": "https://github.com/shyamtawli/devFind"
```

2023-05-06 06:51 UTC, closed without merging

2023-05-06 06:53 UTC, Madanraj0519 commented
Thank you @shyamtawli and sorry @jayk-gupta for delay to make a change in PR